<footer style="padding:25px 0 50px 0; background-image:url('<?php echo $block->getViewFileUrl('img/bg-footer.jpg'); ?>'); background-repeat: repeat-x;  color:#fff;">
	<div class="container">
		<div class="row">
			<div class="col-md-12" style="text-align:center;">
				<img src="<?php echo $block->getViewFileUrl('img/filamtri-icon.png'); ?>" width="80"><br/>
                &copy; <?php echo date('Y') ?> Fil-Am Tri is the leading source for news, training and information in the Filipino Triathlon Community<br/>
                Websites by ClaremontDesign, Inc. All times are in PST (GMT -08:00).
			</div>
		</div>
	</div>
</footer>

