<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand page-scroll" href="index.html">
                <img src="<?php echo $block->getViewFileUrl('img/filamtri-icon.png'); ?>" style="float:left; margin:-20px 10px 0 0;" width="60">
                <span style="color:#0050b2;">Fil</span> <span style="color:#ffcc00">Am</span> <span style="color:#ff0000;">Tri</span>
			</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li class="hidden">
					<a href="#page-top"></a>
				</li>
				<li><a class="page-scroll" href="#about">About</a></li>
				<li><a class="page-scroll" href="#news">News</a></li>
				<li><a class="page-scroll" href="#gallery">Gallery</a></li>
				<li><a class="page-scroll" href="#fatcares">FAT Cares</a></li>
				<li><a class="page-scroll" href="#sponsors">Sponsors</a></li>
				<li><a class="page-scroll" href="#connect">Connect</a></li>
				<li><a class="page-scroll" href="page.html" target="_blank">Page</a></li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>

<!-- Header -->