<section id="about" style="padding:80px 0 80px 0; background-image:url('<?php echo $block->getViewFileUrl('/'); ?>//img/bg-officers.jpg'); background-repeat: repeat-x; background-color:#003399; color:#fff;">
	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				CEO - Arland Macasieb<br/>
				Information System Officer - Daniel Achondo<br/>
				Technology Officer - Cerrone Dayo<br/>
				Admin. Officer/East Coast - Lence Dayo<br/>
				Admin. Officer/West Coast - Noriel Simsuangco<br/><br/>

				East Coast (New York/New Jersey)<br/>
				Brian Salazar - Regional Coordinator<br/>
				Rolan Ocampo - Group Coordinator<br/><br/>

				NorCal<br/>
				JR Calonoc - Group Coordinator<br/>
				Richwood Borja - Training Coordinator/Head Designer<br/>
				Rhonda Bagarino - Administrative Coordinator<br/>
			</div>

			<div class="col-sm-4">
				Los Angeles<br/>
				Greg Uy - Group Coordinator<br/>
				Paulene Williams - Training  Coordinator<br/>
				Andrew Tiotuico - Administrative Coordinator<br/><br/>

				San Diego<br/>
				Aron Sanchez - Group Coordinator<br/>
				Rustico Rasing - Training Coordinator<br/>
				Brian Catacutan - Administrative Coordinator<br/>
			</div>

			<div class="col-sm-4">
				Hawaii
				Efraim Manzano - Regional Coordinator

				Uniform Committee

				Celine Tompkins - Lead Coordinator
				Greg Uy
				Joel Libuano
				Lence Dayo
				Andrew Tiotuico



			</div>
		</div>

	</div>
</section>