<!-- About Section -->
<section id="connect" style="background-image:url('<?php echo $block->getViewFileUrl('/'); ?>/img/bg-follow.jpg'); padding:50px 0 50px 0;">
	<div class="container">
		<div class="row">
			<div class="col-sm-4">

				<!-- start: facebook -->
				<h5>Like & Follow Us On Facebook</h5>
				<div class="fb-page" data-href="https://www.facebook.com/filamtri/?fref=ts" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/filamtri/?fref=ts"><a href="https://www.facebook.com/filamtri/?fref=ts">Fil Am Tri Club</a></blockquote></div></div>
				<!-- end: facebook -->

			</div>
			<div class="col-sm-4">
				<!-- start: twitter -->
				<h5>Like & Follow Us On Facebook</h5>
				<a class="twitter-timeline" href="https://twitter.com/filamtri" data-widget-id="699989913400291328">Tweets by @filamtri</a>
				<script>!function(d, s, id){var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location)?'http':'https'; if (!d.getElementById(id)){js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); }}(document, "script", "twitter-wjs");</script>
				<!-- start: twitter -->
			</div>
			<div class="col-sm-4">
				<h5>Follow Us On Strava</h5>
			</div>
		</div>
	</div>
</section>