<section id="sponsors" style="padding:0;">
	<aside class="clients" style="background-image:url('<?php echo $block->getViewFileUrl('/'); ?>/img/bg-sponsors.jpg'); background-repeat:repeat-x; background-color:#401533;">
		<div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                </div>
            </div>
			<div class="row">
				<div class="col-md-12">
					<div id="Carousel" class="carousel slide">
						<!-- Carousel items -->
						<div class="carousel-inner">
							<div class="item active">
								<div class="row">
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-cdesign.jpg" alt="Image" style="max-width:100%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-taotri.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-xterra.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-circle.jpg" alt="Image" style="max-width:50%;"></a></div>
								</div><!--.row-->
							</div><!--.item-->

							<div class="item">
								<div class="row">
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-boyd.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-erudy.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-octane.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-pbn.jpg" alt="Image" style="max-width:50%;"></a></div>
								</div><!--.row-->
							</div><!--.item-->

							<div class="item">
								<div class="row">
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-unite.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-cdesign.jpg" alt="Image" style="max-width:100%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-taotri.jpg" alt="Image" style="max-width:50%;"></a></div>
									<div class="col-md-3"><a href="#" class="thumbnail"><img src="<?php echo $block->getViewFileUrl('/'); ?>/img/sponsors-xterra.jpg" alt="Image" style="max-width:50%;"></a></div>

								</div><!--.row-->
							</div><!--.item-->

						</div><!--.carousel-inner-->
						<a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>
						<a data-slide="next" href="#Carousel" class="right carousel-control">›</a>
					</div><!--.Carousel-->
				</div>
			</div>
		</div><!--.container-->
	</aside>
</section>