<header>
	<div class="container">
		<div class="intro-text">
            <div style="height:700px;">
            </div>
		</div>
	</div>
</header>

<!-- Services Section -->
<section id="about" style="background-image:url('<?php echo $block->getViewFileUrl('/'); ?>/img/bg-about.jpg'); background-repeat:repeat-x; background-color:#d25c40">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2 class="section-heading">Who We Are</h2>
				<h3 class="section-subheading text-muted">Fil Am Tri Club was founded in 2006 by a small group of Filipinos in NY/NJ.
					Since then, FAT (Fil Am Tri) has grown nationwide and global having members throughout the mainland US, Canada, Hawaii, and of course the homeland in the Philippines. Although comprised mostly of Filipinos, FAT is a non-denominational club accepting all friends and families of Filipino Americans with the mission to grow a network of Filipino triathletes worldwide building a sense of community and fellowship through the medium of endurance sports. We welcome you to become part of the movement! Mabuhay!</h3>
			</div>
		</div>
	</div>
</section>